package com.apostolis.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;

//Database Table with name User
@Entity //This annotation automatically creates the User table in the db
public class User {

    /* //For both TableGenerator and SequenceGenerator default value of allocationSize is 50. 
            //This means that a chunk of 50 values is reserved. In shutdown these reserved values 
            //will be gone. If application is shutdown after only one is used, values from 2 to 50 
            //are gone and next time 51 to 100 will be reserved.
    @Id //For autogenerated id
    @GeneratedValue()
    */
    @SequenceGenerator(name="seqGenWithSize1", allocationSize=1)
    @Id
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seqGenWithSize1")
    private Long id;
    private String username;
    private String name;
    private String email;

    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }


}
